# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostname',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'B28'), (1, 'B2C'), (2, '大数据'), (3, '开发测试'), (4, '运维开发')], default=0),
        ),
    ]
