# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20170713_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostname',
            name='role_type',
        ),
    ]
